### ISSUE TITLE
Moon/End Blessing?

### ISSUE THREAD

**Issue by Andreasss99** [Bawnorton/BetterTrims#66]
What materials give Moon and End Blessing? Can't find it in description. Says Sun blessing is from Gold and Hell's Blessing is from Glowstone. Missing 2 more

Thanks!

**Comment by Bawnorton** [comment]
They're unused currently. Originally End's was provided by ender-pearls but then they'd be too powerful and I plan for moon's to be provided by silver (will require a mod that adds any kind of silver ingot/block)

**Comment by Andreasss99** [comment]
I was honestly thinking you should just make glowstone the ingredient to give both the Moons Blessing & End Blessing together and add the glowing effect to those.

Then leave the gold ingredient as is for the Sun's Blessing and add on the Hell's Blessing to it.

That kinda makes the most sense to me

**Comment by Bawnorton** [comment]
I want to try and keep it at least a bit thematic and 2 blessings is really powerful. In 2.x silver gave the equivalent of moon's blessing and everyone used it because it was the best, I don't want there to be a "best trim", they should each dependent on your situation and play style rather than one just being better than the rest.
